### PR TITLE
Change default SwaggerUI installation path to a more suitable place.

### PR DESCRIPTION
**Pull request by bamkrs**
Installing SwaggerUI in the systems include path just feels wrong.
This PR moves the installation to a more expected and structured place.

On *nix OS's SwaggerUI will be installed to `<install-prefix>`/share/oatpp-`<version>`/oatpp-swagger/res/ (with `<install-prefix>` defaulting to "/usr/local").
On Windows SwaggerUI will be installed to `<install-prefix>`/oatpp-`<version>`/res/ (with `<install-prefix>` defaulting to "c:/Program Files/`${PROJECT_NAME}`").

The installation path can also be overwritten by passing -DOATPP_SWAGGER_UI_INSTALL_DIR="`<dir>`" when invoking cmake.

### CODE REVIEW

**Comment by lganzzzo** [comment]
Hey @bamkrs ,

Looks good!
Please change the destination branch to `1.3.0`

**Review by lganzzzo — APPROVED** [review]
Looks good.
Let's merge it to `1.3.0`

**Comment by bamkrs** [comment]
Check! Since there is no 1.3.0 branch I will create one and will fix the PR description. Somehow the placeholders I marked with `<placeholder>` got lost somewhere. 
Will be the first thing I do tomorrow.

This PR is an requirement to cleanly implement another minor contribution down the line which opens Oat++ for another build-system.

**Comment by bamkrs** [comment]
Hey @lganzzzo could you restart the checks? I rebased everything to oatpp:v1.3.0 and the tests should run smoothly now!

**Comment by lganzzzo** [comment]
Looks great!

**Pull request merged**
